[Soo] 프로젝트 생성 및 요구사항 선정
learn-a-thon/my-tiny-world pull request #4
Opened 2023-03-26 10:31 UTC by suchan7311

1. 쿠폰 발급 시스템
    1. 대량의 발급요청 처리
    2. 쿠폰 만료 처리
    3. 선착순 인원 쿠폰 발급 기능
2. 특정 상황에서의 슬랙 봇 연동을 통한 알림 기능 (추가 요구사항에 구현할지 고민이됩니다.)

2023-03-26 10:54 UTC, doorisopen requested changes
destination branch 확인 부탁드릴게요~~ 
`main`이 아닌 개인 메인 브랜치(`Soo`)를 사용하시면 됩니다. 자세한 내용은 [README](https://github.com/learn-a-thon/my-tiny-world#how-to-do-it)를 참고해주세요!

2023-03-26 12:48 UTC, leejaeyeong approved these changes

2023-03-31 08:45 UTC, doorisopen commented
브랜치 병합 이후에 아래 내용 참고해서 진행해보세요!
https://github.com/learn-a-thon/my-tiny-world/discussions/6

2023-03-31 08:57 UTC, doorisopen approved these changes

2023-03-31 09:00 UTC, doorisopen commented
learn-a-thon:Soo<--- suchan7311:main 브랜치로 하셔도 무관하긴한데

learn-a-thon:Soo<--- suchan7311:Soo로 하심이 나중에 편할 수도 있을 듯하니 참고부탁드립니다ㅎㅎ

2023-04-02 13:38 UTC, merged